# -*- coding: utf-8 -*-
"""email_validation.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q1ZT9AJPY1SqbgOO7T_sMjoq3qykDtje
"""

email = input('Enter your Email: ')
k, j, d = 0, 0, 0

if len(email) >= 6:
    if email[0].isalpha():
        if "@" in email and email.count("@") == 1:
            domain = email.split("@")[1]
            if "." in domain:
                if domain[-4] == "." or domain[-3] == ".":
                    for i in email:
                        if i.isspace():
                            k = 1
                        elif i.isalpha():
                            if i == i.upper():
                                j = 1
                        elif i.isdigit():
                            continue
                        elif i == "_" or i == "." or i == "@":
                            continue
                        else:
                            d = 1
                    if k == 1 or j == 1 or d == 1:
                        print("Wrong email. Do not use any spaces or uppercase letters.")
                else:
                    print("Wrong email format. Missing dot in domain part.")
            else:
                print("Wrong email format. Missing dot in domain part.")
        else:
            print("Wrong email format. Use only one @")
    else:
        print("Wrong email format. Use alphabet as the first character.")
else:
    print("Wrong email format. Use more than 6 characters.")